[program:ipop-factory]
command=/root/ipop-factory.py loop --max-workers 4 --limit 4 --interval 30 --timeout 900
autostart=true
autorestart=true
stdout_logfile=/tmp/ipop-factory.log
stderr_logfile=/tmp/ipop-factory.log
priority=30
